---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "15 8-22 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Dockerfile
      - files/**
      - patches/**
      - scripts/**
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Dockerfile
      - files/**
      - patches/**
      - scripts/**

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '2.11'
          - '3.2'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/manager-runner
          VERSION: ${{ matrix.version }}
      - run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/manager-runner
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'osism/container-image-manager-runner' &&
          github.ref == 'refs/heads/main'
